wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1684409761.010939
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 23
      4: 3.10.11
      5: 0.15.3
      8:
      - 3
      - 5
